-- Generated by the protocol buffer compiler.  DO NOT EDIT!
-- source: unittest.proto

pragma Ada_2012;

package Unittest.ImportMessage is
  type Instance is new Protocol_Buffers.Message.Instance with private;
  type ImportMessage_Access is access all Instance;

  ---------------------------------------------------------------------------
  -- Inherited functions and procedures from Protocol_Buffers.Message -------
  ---------------------------------------------------------------------------

  overriding
  procedure Clear
    (The_Message : in out Unittest.ImportMessage.Instance);

  overriding
  procedure Serialize_With_Cached_Sizes
    (The_Message   : in Unittest.ImportMessage.Instance;
     The_Coded_Output_Stream : in
       Protocol_Buffers.IO.Coded_Output_Stream.Instance);

  overriding
  procedure Merge_Partial_From_Coded_Input_Stream
    (The_Message   : in out Unittest.ImportMessage.Instance;
     The_Coded_Input_Stream : in out
       Protocol_Buffers.IO.Coded_Input_Stream.Instance);

  overriding
  procedure Merge
    (To   : in out Unittest.ImportMessage.Instance;
     From : in Unittest.ImportMessage.Instance);

  overriding
  procedure Copy
    (To   : in out Unittest.ImportMessage.Instance;
     From : in Unittest.ImportMessage.Instance);

  overriding
  function Get_Type_Name
    (The_Message : in Unittest.ImportMessage.Instance) return Protocol_Buffers.Wire_Format.PB_String;

  overriding
  function Byte_Size
    (The_Message : in out Unittest.ImportMessage.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Get_Cached_Size
    (The_Message : in Unittest.ImportMessage.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Is_Initialized
    (The_Message : in Unittest.ImportMessage.Instance) return Boolean;

  overriding
  procedure Finalize (The_Message : in out Unittest.ImportMessage.Instance);

  ---------------------------------------------------------------------------
  -- Field accessor declarations --------------------------------------------
  ---------------------------------------------------------------------------

  -- optional int32 d = 1;
  function Has_D
    (The_Message : in ImportMessage.Instance) return Boolean;
  procedure Clear_D
    (The_Message : in out ImportMessage.Instance);
  function Get_D
    (The_Message : in ImportMessage.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_D
    (The_Message : in out ImportMessage.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

private
  type Instance is new Protocol_Buffers.Message.Instance with record
    D : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Has_Bits : Protocol_Buffers.Wire_Format.Has_Bits_Array_Type (0 .. (1 + 31) / 32) := (others => 0);
    Cached_Size : Protocol_Buffers.Wire_Format.PB_Object_Size := 0;
  end record;

  procedure Set_Has_D (The_Message : in out Unittest.ImportMessage.Instance);
  procedure Clear_Has_D (The_Message : in out Unittest.ImportMessage.Instance);
end Unittest.ImportMessage;
