-- Generated by the protocol buffer compiler.  DO NOT EDIT!
-- source: unittest.proto

pragma Ada_2012;

package Unittest.TestRequired is
  type Instance is new Protocol_Buffers.Message.Instance with private;
  type TestRequired_Access is access all Instance;

  ---------------------------------------------------------------------------
  -- Inherited functions and procedures from Protocol_Buffers.Message -------
  ---------------------------------------------------------------------------

  overriding
  procedure Clear
    (The_Message : in out Unittest.TestRequired.Instance);

  overriding
  procedure Serialize_With_Cached_Sizes
    (The_Message   : in Unittest.TestRequired.Instance;
     The_Coded_Output_Stream : in
       Protocol_Buffers.IO.Coded_Output_Stream.Instance);

  overriding
  procedure Merge_Partial_From_Coded_Input_Stream
    (The_Message   : in out Unittest.TestRequired.Instance;
     The_Coded_Input_Stream : in out
       Protocol_Buffers.IO.Coded_Input_Stream.Instance);

  overriding
  procedure Merge
    (To   : in out Unittest.TestRequired.Instance;
     From : in Unittest.TestRequired.Instance);

  overriding
  procedure Copy
    (To   : in out Unittest.TestRequired.Instance;
     From : in Unittest.TestRequired.Instance);

  overriding
  function Get_Type_Name
    (The_Message : in Unittest.TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_String;

  overriding
  function Byte_Size
    (The_Message : in out Unittest.TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Get_Cached_Size
    (The_Message : in Unittest.TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Is_Initialized
    (The_Message : in Unittest.TestRequired.Instance) return Boolean;

  overriding
  procedure Finalize (The_Message : in out Unittest.TestRequired.Instance);

  ---------------------------------------------------------------------------
  -- Field accessor declarations --------------------------------------------
  ---------------------------------------------------------------------------

  -- required int32 a = 1;
  function Has_A
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_A
    (The_Message : in out TestRequired.Instance);
  function Get_A
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_A
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy2 = 2;
  function Has_Dummy2
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy2
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy2
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy2
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- required int32 b = 3;
  function Has_B
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_B
    (The_Message : in out TestRequired.Instance);
  function Get_B
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_B
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy4 = 4;
  function Has_Dummy4
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy4
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy4
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy4
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy5 = 5;
  function Has_Dummy5
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy5
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy5
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy5
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy6 = 6;
  function Has_Dummy6
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy6
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy6
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy6
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy7 = 7;
  function Has_Dummy7
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy7
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy7
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy7
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy8 = 8;
  function Has_Dummy8
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy8
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy8
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy8
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy9 = 9;
  function Has_Dummy9
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy9
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy9
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy9
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy10 = 10;
  function Has_Dummy10
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy10
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy10
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy10
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy11 = 11;
  function Has_Dummy11
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy11
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy11
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy11
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy12 = 12;
  function Has_Dummy12
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy12
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy12
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy12
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy13 = 13;
  function Has_Dummy13
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy13
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy13
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy13
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy14 = 14;
  function Has_Dummy14
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy14
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy14
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy14
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy15 = 15;
  function Has_Dummy15
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy15
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy15
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy15
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy16 = 16;
  function Has_Dummy16
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy16
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy16
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy16
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy17 = 17;
  function Has_Dummy17
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy17
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy17
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy17
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy18 = 18;
  function Has_Dummy18
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy18
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy18
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy18
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy19 = 19;
  function Has_Dummy19
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy19
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy19
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy19
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy20 = 20;
  function Has_Dummy20
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy20
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy20
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy20
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy21 = 21;
  function Has_Dummy21
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy21
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy21
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy21
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy22 = 22;
  function Has_Dummy22
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy22
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy22
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy22
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy23 = 23;
  function Has_Dummy23
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy23
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy23
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy23
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy24 = 24;
  function Has_Dummy24
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy24
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy24
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy24
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy25 = 25;
  function Has_Dummy25
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy25
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy25
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy25
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy26 = 26;
  function Has_Dummy26
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy26
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy26
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy26
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy27 = 27;
  function Has_Dummy27
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy27
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy27
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy27
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy28 = 28;
  function Has_Dummy28
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy28
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy28
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy28
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy29 = 29;
  function Has_Dummy29
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy29
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy29
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy29
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy30 = 30;
  function Has_Dummy30
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy30
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy30
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy30
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy31 = 31;
  function Has_Dummy31
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy31
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy31
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy31
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 dummy32 = 32;
  function Has_Dummy32
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_Dummy32
    (The_Message : in out TestRequired.Instance);
  function Get_Dummy32
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy32
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- required int32 c = 33;
  function Has_C
    (The_Message : in TestRequired.Instance) return Boolean;
  procedure Clear_C
    (The_Message : in out TestRequired.Instance);
  function Get_C
    (The_Message : in TestRequired.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_C
    (The_Message : in out TestRequired.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

private
  type Instance is new Protocol_Buffers.Message.Instance with record
    A : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy2 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    B : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy4 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy5 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy6 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy7 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy8 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy9 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy10 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy11 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy12 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy13 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy14 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy15 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy16 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy17 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy18 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy19 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy20 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy21 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy22 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy23 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy24 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy25 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy26 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy27 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy28 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy29 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy30 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy31 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Dummy32 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    C : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Has_Bits : Protocol_Buffers.Wire_Format.Has_Bits_Array_Type (0 .. (33 + 31) / 32) := (others => 0);
    Cached_Size : Protocol_Buffers.Wire_Format.PB_Object_Size := 0;
  end record;

  procedure Set_Has_A (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_A (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy2 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy2 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_B (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_B (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy4 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy4 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy5 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy5 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy6 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy6 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy7 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy7 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy8 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy8 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy9 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy9 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy10 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy10 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy11 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy11 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy12 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy12 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy13 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy13 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy14 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy14 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy15 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy15 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy16 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy16 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy17 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy17 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy18 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy18 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy19 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy19 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy20 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy20 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy21 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy21 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy22 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy22 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy23 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy23 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy24 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy24 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy25 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy25 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy26 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy26 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy27 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy27 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy28 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy28 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy29 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy29 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy30 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy30 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy31 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy31 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_Dummy32 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_Dummy32 (The_Message : in out Unittest.TestRequired.Instance);
  procedure Set_Has_C (The_Message : in out Unittest.TestRequired.Instance);
  procedure Clear_Has_C (The_Message : in out Unittest.TestRequired.Instance);
end Unittest.TestRequired;
