-- Generated by the protocol buffer compiler.  DO NOT EDIT!
-- source: unittest.proto

pragma Ada_2012;

limited with Unittest.TestRequired;

package Unittest.TestRequiredForeign is
  type Instance is new Protocol_Buffers.Message.Instance with private;
  type TestRequiredForeign_Access is access all Instance;

  ---------------------------------------------------------------------------
  -- Inherited functions and procedures from Protocol_Buffers.Message -------
  ---------------------------------------------------------------------------

  overriding
  procedure Clear
    (The_Message : in out Unittest.TestRequiredForeign.Instance);

  overriding
  procedure Serialize_With_Cached_Sizes
    (The_Message   : in Unittest.TestRequiredForeign.Instance;
     The_Coded_Output_Stream : in
       Protocol_Buffers.IO.Coded_Output_Stream.Instance);

  overriding
  procedure Merge_Partial_From_Coded_Input_Stream
    (The_Message   : in out Unittest.TestRequiredForeign.Instance;
     The_Coded_Input_Stream : in out
       Protocol_Buffers.IO.Coded_Input_Stream.Instance);

  overriding
  procedure Merge
    (To   : in out Unittest.TestRequiredForeign.Instance;
     From : in Unittest.TestRequiredForeign.Instance);

  overriding
  procedure Copy
    (To   : in out Unittest.TestRequiredForeign.Instance;
     From : in Unittest.TestRequiredForeign.Instance);

  overriding
  function Get_Type_Name
    (The_Message : in Unittest.TestRequiredForeign.Instance) return Protocol_Buffers.Wire_Format.PB_String;

  overriding
  function Byte_Size
    (The_Message : in out Unittest.TestRequiredForeign.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Get_Cached_Size
    (The_Message : in Unittest.TestRequiredForeign.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Is_Initialized
    (The_Message : in Unittest.TestRequiredForeign.Instance) return Boolean;

  overriding
  procedure Finalize (The_Message : in out Unittest.TestRequiredForeign.Instance);

  ---------------------------------------------------------------------------
  -- Field accessor declarations --------------------------------------------
  ---------------------------------------------------------------------------

  -- optional .protobuf_unittest.TestRequired optional_message = 1;
  function Has_Optional_Message
    (The_Message : in TestRequiredForeign.Instance) return Boolean;
  procedure Clear_Optional_Message
    (The_Message : in out TestRequiredForeign.Instance);
  function Get_Optional_Message
    (The_Message : in out TestRequiredForeign.Instance) return access Unittest.TestRequired.Instance;
  function Release_Optional_Message
    (The_Message : in out TestRequiredForeign.Instance) return access Unittest.TestRequired.Instance;
  procedure Set_Optional_Message
    (The_Message : in out TestRequiredForeign.Instance;
     Value : in Unittest.TestRequired.TestRequired_Access);

  -- repeated .protobuf_unittest.TestRequired repeated_message = 2;
  function Repeated_Message_Size
    (The_Message : in TestRequiredForeign.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;
  procedure Clear_Repeated_Message
    (The_Message : in out TestRequiredForeign.Instance);
  function Get_Repeated_Message
    (The_Message : in TestRequiredForeign.Instance;
     Index : in Protocol_Buffers.Wire_Format.PB_Object_Size) return access Unittest.TestRequired.Instance;
  function Add_Repeated_Message
    (The_Message : in out TestRequiredForeign.Instance) return access Unittest.TestRequired.Instance;

  -- optional int32 dummy = 3;
  function Has_Dummy
    (The_Message : in TestRequiredForeign.Instance) return Boolean;
  procedure Clear_Dummy
    (The_Message : in out TestRequiredForeign.Instance);
  function Get_Dummy
    (The_Message : in TestRequiredForeign.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Dummy
    (The_Message : in out TestRequiredForeign.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

private
  type Instance is new Protocol_Buffers.Message.Instance with record
    Optional_Message : access Unittest.TestRequired.Instance;
    Repeated_Message : Protocol_Buffers.Message.Message_Vector.Vector;
    Dummy : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Has_Bits : Protocol_Buffers.Wire_Format.Has_Bits_Array_Type (0 .. (3 + 31) / 32) := (others => 0);
    Cached_Size : Protocol_Buffers.Wire_Format.PB_Object_Size := 0;
  end record;

  procedure Set_Has_Optional_Message (The_Message : in out Unittest.TestRequiredForeign.Instance);
  procedure Clear_Has_Optional_Message (The_Message : in out Unittest.TestRequiredForeign.Instance);
  procedure Set_Has_Dummy (The_Message : in out Unittest.TestRequiredForeign.Instance);
  procedure Clear_Has_Dummy (The_Message : in out Unittest.TestRequiredForeign.Instance);
end Unittest.TestRequiredForeign;
