-- Generated by the protocol buffer compiler.  DO NOT EDIT!
-- source: unittest.proto

pragma Ada_2012;

package body Unittest.OneBytes is
  ---------------------------------------------------------------------------
  -- Inherited functions and procedures from Protocol_Buffers.Message -------
  ---------------------------------------------------------------------------

  procedure Clear
    (The_Message : in out Unittest.OneBytes.Instance) is
  begin
    if (The_Message.Has_Bits (0 / 32) and Protocol_Buffers.Wire_Format.Shift_Left (16#FF#, 0 mod 32)) /= 0 then
      if The_Message.Has_Data then
        The_Message.Clear_Has_Data;
        declare
          procedure Free is new Ada.Unchecked_Deallocation (Protocol_Buffers.Wire_Format.PB_String, Protocol_Buffers.Wire_Format.PB_String_Access);
        begin
          if The_Message.Data /= Protocol_Buffers.Generated_Message_Utilities.EMPTY_STRING'Access then
            Free (The_Message.Data);
          end if;
        end;
        The_Message.Data := Protocol_Buffers.Generated_Message_Utilities.EMPTY_STRING'Access;
      end if;
    end if;
    The_Message.Has_Bits := (others => 0);
  end Clear;

  procedure Copy
    (To   : in out Unittest.OneBytes.Instance;
     From : in Unittest.OneBytes.Instance) is
  begin
    To.Clear;
    To.Merge (From);
  end Copy;

  function Get_Type_Name
    (The_Message : in Unittest.OneBytes.Instance) return Protocol_Buffers.Wire_Format.PB_String is
  begin
    return "protobuf_unittest.OneBytes";
  end Get_Type_Name;

  function Is_Initialized
    (The_Message : in Unittest.OneBytes.Instance) return Boolean is
  begin
    return True;
  end Is_Initialized;

  procedure Merge
    (To   : in out Unittest.OneBytes.Instance;
     From : in Unittest.OneBytes.Instance) is
  begin
    if (From.Has_Bits (0 / 32) and Protocol_Buffers.Wire_Format.Shift_Left (16#FF#, 0 mod 32)) /= 0 then
      -- optional bytes data = 1;
      if From.Has_Data then
        To.Set_Data(From.Get_Data);
      end if;
    end if;
  end Merge;

  function Byte_Size
    (The_Message : in out Unittest.OneBytes.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size is
    Total_Size : Protocol_Buffers.Wire_Format.PB_Object_Size := 0;
  begin
    if (The_Message.Has_Bits (0 / 32) and Protocol_Buffers.Wire_Format.Shift_Left (16#FF#, 0 mod 32)) /= 0 then
      -- optional bytes data = 1;
      if The_Message.Has_Data then
        Total_Size := Total_Size + 1 + Protocol_Buffers.IO.Coded_Output_Stream.Compute_String_Size_No_Tag (The_Message.Data.all);
      end if;
    end if;
    The_Message.Cached_Size := Total_Size;
    return Total_Size;
  end Byte_Size;

  procedure Serialize_With_Cached_Sizes
    (The_Message   : in Unittest.OneBytes.Instance;
     The_Coded_Output_Stream : in
       Protocol_Buffers.IO.Coded_Output_Stream.Instance) is
  begin
    -- optional bytes data = 1;
    if The_Message.Has_Data then
      The_Coded_Output_Stream.Write_String (1, The_Message.Data.all);
    end if;
  end Serialize_With_Cached_Sizes;

  procedure Merge_Partial_From_Coded_Input_Stream
    (The_Message   : in out Unittest.OneBytes.Instance;
     The_Coded_Input_Stream : in out
       Protocol_Buffers.IO.Coded_Input_Stream.Instance) is
    Tag : Protocol_Buffers.Wire_Format.PB_UInt32;
  begin
    Tag := The_Coded_Input_Stream.Read_Tag;
    while Tag /= 0 loop
      case Protocol_Buffers.Wire_Format.Get_Tag_Field_Number (Tag) is
      -- optional bytes data = 1;
      when 1 =>
        if Protocol_Buffers.Wire_Format.Get_Tag_Wire_Type (Tag) =
          Protocol_Buffers.Wire_Format.LENGTH_DELIMITED then
          declare
            procedure Free is new Ada.Unchecked_Deallocation (Protocol_Buffers.Wire_Format.PB_String, Protocol_Buffers.Wire_Format.PB_String_Access);
          begin
            if The_Message.Data /= Protocol_Buffers.Generated_Message_Utilities.EMPTY_STRING'Access then
              Free (The_Message.Data);
            end if;
          end;
          The_Message.Set_Has_Data;
          The_Message.Data := The_Coded_Input_Stream.Read_String;
        end if;
      when others =>
        declare
          Dummy : Protocol_Buffers.Wire_Format.PB_Bool;
          pragma Unreferenced (Dummy);
        begin
          Dummy := The_Coded_Input_Stream.Skip_Field (Tag);
          return;
        end;
      end case;
      Tag := The_Coded_Input_Stream.Read_Tag;
    end loop;
  end Merge_Partial_From_Coded_Input_Stream;

  function Get_Cached_Size
    (The_Message : in Unittest.OneBytes.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size is
  begin
    return The_Message.Cached_Size;
  end Get_Cached_Size;

  overriding
  procedure Finalize
    (The_Message : in out Unittest.OneBytes.Instance) is
  begin
    declare
      procedure Free is new Ada.Unchecked_Deallocation (Protocol_Buffers.Wire_Format.PB_String, Protocol_Buffers.Wire_Format.PB_String_Access);
    begin
      if The_Message.Data /= Protocol_Buffers.Generated_Message_Utilities.EMPTY_STRING'Access then
        Free (The_Message.Data);
      end if;
    end;
  end Finalize;

  ---------------------------------------------------------------------------
  -- Field accessor definitions ---------------------------------------------
  ---------------------------------------------------------------------------

  -- optional bytes data = 1;
  function Has_Data
    (The_Message : in OneBytes.Instance) return Boolean is
  begin
    return (The_Message.Has_Bits(0) and 16#00000001#) /= 0;
  end Has_Data;

  procedure Set_Has_Data
    (The_Message : in out OneBytes.Instance) is
  begin
    The_Message.Has_Bits(0) := The_Message.Has_Bits(0) or 16#00000001#;
  end Set_Has_Data;

  procedure Clear_Has_Data
    (The_Message : in out OneBytes.Instance) is
  begin
    The_Message.Has_Bits(0) := The_Message.Has_Bits(0) and (not 16#00000001#);
  end Clear_Has_Data;

  procedure Clear_Data
    (The_Message : in out OneBytes.Instance) is
  begin
    The_Message.Clear_Has_Data;
    declare
      procedure Free is new Ada.Unchecked_Deallocation (Protocol_Buffers.Wire_Format.PB_String, Protocol_Buffers.Wire_Format.PB_String_Access);
    begin
      if The_Message.Data /= Protocol_Buffers.Generated_Message_Utilities.EMPTY_STRING'Access then
        Free (The_Message.Data);
      end if;
    end;
    The_Message.Data := Protocol_Buffers.Generated_Message_Utilities.EMPTY_STRING'Access;
    The_Message.Clear_Has_Data;
  end Clear_Data;

  function Get_Data
    (The_Message : in OneBytes.Instance) return Protocol_Buffers.Wire_Format.PB_String is
  begin
    return The_Message.Data.all;
  end Get_Data;

  function Get_Data
    (The_Message : in out OneBytes.Instance;
     Size : in Integer := -1) return Protocol_Buffers.Wire_Format.PB_String_Access is
  begin
    The_Message.Set_Has_Data;
    if Size >= 0 then
      declare
        procedure Free is new Ada.Unchecked_Deallocation (Protocol_Buffers.Wire_Format.PB_String, Protocol_Buffers.Wire_Format.PB_String_Access);
      begin
        if The_Message.Data /= Protocol_Buffers.Generated_Message_Utilities.EMPTY_STRING'Access then
          Free (The_Message.Data);
        end if;
      end;
      The_Message.Data := new Protocol_Buffers.Wire_Format.PB_String'(1 .. Size => Character'Val (0));
      return The_Message.Data;
    end if;

    if The_Message.Data = Protocol_Buffers.Generated_Message_Utilities.EMPTY_STRING'Access then
      The_Message.Data := new String'(Protocol_Buffers.Generated_Message_Utilities.EMPTY_STRING);
    end if;
    return The_Message.Data;
  end Get_Data;

  procedure Set_Data
    (The_Message : in out OneBytes.Instance;
     Value : in Protocol_Buffers.Wire_Format.PB_String) is
  begin
    The_Message.Set_Has_Data;
    if The_Message.Data /= Protocol_Buffers.Generated_Message_Utilities.EMPTY_STRING'Access and then Value'Length = The_Message.Data.all'Length then
      The_Message.Data.all := Value;
    else
      declare
        procedure Free is new Ada.Unchecked_Deallocation (Protocol_Buffers.Wire_Format.PB_String, Protocol_Buffers.Wire_Format.PB_String_Access);
      begin
        if The_Message.Data /= Protocol_Buffers.Generated_Message_Utilities.EMPTY_STRING'Access then
          Free (The_Message.Data);
        end if;
      end;
      The_Message.Data := new Protocol_Buffers.Wire_Format.PB_String'(Value);
    end if;
  end Set_Data;

  function Release_Data
    (The_Message : in out OneBytes.Instance) return Protocol_Buffers.Wire_Format.PB_String_Access is
  begin
    The_Message.Clear_Has_Data;
    if The_Message.Data = Protocol_Buffers.Generated_Message_Utilities.EMPTY_STRING'Access then
      return null;
    else
      declare
        Temp : Protocol_Buffers.Wire_Format.PB_String_Access := The_Message.Data;
      begin
        The_Message.Data := Protocol_Buffers.Generated_Message_Utilities.EMPTY_STRING'Access;
        return Temp;
      end;
    end if;
  end Release_Data;

end Unittest.OneBytes;
