-- Generated by the protocol buffer compiler.  DO NOT EDIT!
-- source: unittest.proto

pragma Ada_2012;

package Unittest.OneString is
  type Instance is new Protocol_Buffers.Message.Instance with private;
  type OneString_Access is access all Instance;

  ---------------------------------------------------------------------------
  -- Inherited functions and procedures from Protocol_Buffers.Message -------
  ---------------------------------------------------------------------------

  overriding
  procedure Clear
    (The_Message : in out Unittest.OneString.Instance);

  overriding
  procedure Serialize_With_Cached_Sizes
    (The_Message   : in Unittest.OneString.Instance;
     The_Coded_Output_Stream : in
       Protocol_Buffers.IO.Coded_Output_Stream.Instance);

  overriding
  procedure Merge_Partial_From_Coded_Input_Stream
    (The_Message   : in out Unittest.OneString.Instance;
     The_Coded_Input_Stream : in out
       Protocol_Buffers.IO.Coded_Input_Stream.Instance);

  overriding
  procedure Merge
    (To   : in out Unittest.OneString.Instance;
     From : in Unittest.OneString.Instance);

  overriding
  procedure Copy
    (To   : in out Unittest.OneString.Instance;
     From : in Unittest.OneString.Instance);

  overriding
  function Get_Type_Name
    (The_Message : in Unittest.OneString.Instance) return Protocol_Buffers.Wire_Format.PB_String;

  overriding
  function Byte_Size
    (The_Message : in out Unittest.OneString.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Get_Cached_Size
    (The_Message : in Unittest.OneString.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Is_Initialized
    (The_Message : in Unittest.OneString.Instance) return Boolean;

  overriding
  procedure Finalize (The_Message : in out Unittest.OneString.Instance);

  ---------------------------------------------------------------------------
  -- Field accessor declarations --------------------------------------------
  ---------------------------------------------------------------------------

  -- optional string data = 1;
  function Has_Data
    (The_Message : in OneString.Instance) return Boolean;
  procedure Clear_Data
    (The_Message : in out OneString.Instance);
  function Get_Data
    (The_Message : in OneString.Instance) return Protocol_Buffers.Wire_Format.PB_String;
  function Get_Data
    (The_Message : in out OneString.Instance; Size : in Integer := -1) return Protocol_Buffers.Wire_Format.PB_String_Access;
  procedure Set_Data
    (The_Message : in out OneString.Instance;
     Value : in Protocol_Buffers.Wire_Format.PB_String);
  function Release_Data
    (The_Message : in out OneString.Instance) return Protocol_Buffers.Wire_Format.PB_String_Access;

private
  type Instance is new Protocol_Buffers.Message.Instance with record
    Data : Protocol_Buffers.Wire_Format.PB_String_Access := Protocol_Buffers.Generated_Message_Utilities.EMPTY_STRING'Access;
    Has_Bits : Protocol_Buffers.Wire_Format.Has_Bits_Array_Type (0 .. (1 + 31) / 32) := (others => 0);
    Cached_Size : Protocol_Buffers.Wire_Format.PB_Object_Size := 0;
  end record;

  procedure Set_Has_Data (The_Message : in out Unittest.OneString.Instance);
  procedure Clear_Has_Data (The_Message : in out Unittest.OneString.Instance);
end Unittest.OneString;
