-- Generated by the protocol buffer compiler.  DO NOT EDIT!
-- source: unittest.proto

pragma Ada_2012;

package Unittest.TestReallyLargeTagNumber is
  type Instance is new Protocol_Buffers.Message.Instance with private;
  type TestReallyLargeTagNumber_Access is access all Instance;

  ---------------------------------------------------------------------------
  -- Inherited functions and procedures from Protocol_Buffers.Message -------
  ---------------------------------------------------------------------------

  overriding
  procedure Clear
    (The_Message : in out Unittest.TestReallyLargeTagNumber.Instance);

  overriding
  procedure Serialize_With_Cached_Sizes
    (The_Message   : in Unittest.TestReallyLargeTagNumber.Instance;
     The_Coded_Output_Stream : in
       Protocol_Buffers.IO.Coded_Output_Stream.Instance);

  overriding
  procedure Merge_Partial_From_Coded_Input_Stream
    (The_Message   : in out Unittest.TestReallyLargeTagNumber.Instance;
     The_Coded_Input_Stream : in out
       Protocol_Buffers.IO.Coded_Input_Stream.Instance);

  overriding
  procedure Merge
    (To   : in out Unittest.TestReallyLargeTagNumber.Instance;
     From : in Unittest.TestReallyLargeTagNumber.Instance);

  overriding
  procedure Copy
    (To   : in out Unittest.TestReallyLargeTagNumber.Instance;
     From : in Unittest.TestReallyLargeTagNumber.Instance);

  overriding
  function Get_Type_Name
    (The_Message : in Unittest.TestReallyLargeTagNumber.Instance) return Protocol_Buffers.Wire_Format.PB_String;

  overriding
  function Byte_Size
    (The_Message : in out Unittest.TestReallyLargeTagNumber.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Get_Cached_Size
    (The_Message : in Unittest.TestReallyLargeTagNumber.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Is_Initialized
    (The_Message : in Unittest.TestReallyLargeTagNumber.Instance) return Boolean;

  overriding
  procedure Finalize (The_Message : in out Unittest.TestReallyLargeTagNumber.Instance);

  ---------------------------------------------------------------------------
  -- Field accessor declarations --------------------------------------------
  ---------------------------------------------------------------------------

  -- optional int32 a = 1;
  function Has_A
    (The_Message : in TestReallyLargeTagNumber.Instance) return Boolean;
  procedure Clear_A
    (The_Message : in out TestReallyLargeTagNumber.Instance);
  function Get_A
    (The_Message : in TestReallyLargeTagNumber.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_A
    (The_Message : in out TestReallyLargeTagNumber.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- optional int32 bb = 268435455;
  function Has_Bb
    (The_Message : in TestReallyLargeTagNumber.Instance) return Boolean;
  procedure Clear_Bb
    (The_Message : in out TestReallyLargeTagNumber.Instance);
  function Get_Bb
    (The_Message : in TestReallyLargeTagNumber.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Bb
    (The_Message : in out TestReallyLargeTagNumber.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

private
  type Instance is new Protocol_Buffers.Message.Instance with record
    A : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Bb : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Has_Bits : Protocol_Buffers.Wire_Format.Has_Bits_Array_Type (0 .. (2 + 31) / 32) := (others => 0);
    Cached_Size : Protocol_Buffers.Wire_Format.PB_Object_Size := 0;
  end record;

  procedure Set_Has_A (The_Message : in out Unittest.TestReallyLargeTagNumber.Instance);
  procedure Clear_Has_A (The_Message : in out Unittest.TestReallyLargeTagNumber.Instance);
  procedure Set_Has_Bb (The_Message : in out Unittest.TestReallyLargeTagNumber.Instance);
  procedure Clear_Has_Bb (The_Message : in out Unittest.TestReallyLargeTagNumber.Instance);
end Unittest.TestReallyLargeTagNumber;
