-- Generated by the protocol buffer compiler.  DO NOT EDIT!
-- source: unittest.proto

pragma Ada_2012;

limited with Unittest.TestMutualRecursionA;

package Unittest.TestMutualRecursionB is
  type Instance is new Protocol_Buffers.Message.Instance with private;
  type TestMutualRecursionB_Access is access all Instance;

  ---------------------------------------------------------------------------
  -- Inherited functions and procedures from Protocol_Buffers.Message -------
  ---------------------------------------------------------------------------

  overriding
  procedure Clear
    (The_Message : in out Unittest.TestMutualRecursionB.Instance);

  overriding
  procedure Serialize_With_Cached_Sizes
    (The_Message   : in Unittest.TestMutualRecursionB.Instance;
     The_Coded_Output_Stream : in
       Protocol_Buffers.IO.Coded_Output_Stream.Instance);

  overriding
  procedure Merge_Partial_From_Coded_Input_Stream
    (The_Message   : in out Unittest.TestMutualRecursionB.Instance;
     The_Coded_Input_Stream : in out
       Protocol_Buffers.IO.Coded_Input_Stream.Instance);

  overriding
  procedure Merge
    (To   : in out Unittest.TestMutualRecursionB.Instance;
     From : in Unittest.TestMutualRecursionB.Instance);

  overriding
  procedure Copy
    (To   : in out Unittest.TestMutualRecursionB.Instance;
     From : in Unittest.TestMutualRecursionB.Instance);

  overriding
  function Get_Type_Name
    (The_Message : in Unittest.TestMutualRecursionB.Instance) return Protocol_Buffers.Wire_Format.PB_String;

  overriding
  function Byte_Size
    (The_Message : in out Unittest.TestMutualRecursionB.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Get_Cached_Size
    (The_Message : in Unittest.TestMutualRecursionB.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Is_Initialized
    (The_Message : in Unittest.TestMutualRecursionB.Instance) return Boolean;

  overriding
  procedure Finalize (The_Message : in out Unittest.TestMutualRecursionB.Instance);

  ---------------------------------------------------------------------------
  -- Field accessor declarations --------------------------------------------
  ---------------------------------------------------------------------------

  -- optional .protobuf_unittest.TestMutualRecursionA a = 1;
  function Has_A
    (The_Message : in TestMutualRecursionB.Instance) return Boolean;
  procedure Clear_A
    (The_Message : in out TestMutualRecursionB.Instance);
  function Get_A
    (The_Message : in out TestMutualRecursionB.Instance) return access Unittest.TestMutualRecursionA.Instance;
  function Release_A
    (The_Message : in out TestMutualRecursionB.Instance) return access Unittest.TestMutualRecursionA.Instance;
  procedure Set_A
    (The_Message : in out TestMutualRecursionB.Instance;
     Value : in Unittest.TestMutualRecursionA.TestMutualRecursionA_Access);

  -- optional int32 optional_int32 = 2;
  function Has_Optional_Int32
    (The_Message : in TestMutualRecursionB.Instance) return Boolean;
  procedure Clear_Optional_Int32
    (The_Message : in out TestMutualRecursionB.Instance);
  function Get_Optional_Int32
    (The_Message : in TestMutualRecursionB.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Optional_Int32
    (The_Message : in out TestMutualRecursionB.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

private
  type Instance is new Protocol_Buffers.Message.Instance with record
    A : access Unittest.TestMutualRecursionA.Instance;
    Optional_Int32 : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Has_Bits : Protocol_Buffers.Wire_Format.Has_Bits_Array_Type (0 .. (2 + 31) / 32) := (others => 0);
    Cached_Size : Protocol_Buffers.Wire_Format.PB_Object_Size := 0;
  end record;

  procedure Set_Has_A (The_Message : in out Unittest.TestMutualRecursionB.Instance);
  procedure Clear_Has_A (The_Message : in out Unittest.TestMutualRecursionB.Instance);
  procedure Set_Has_Optional_Int32 (The_Message : in out Unittest.TestMutualRecursionB.Instance);
  procedure Clear_Has_Optional_Int32 (The_Message : in out Unittest.TestMutualRecursionB.Instance);
end Unittest.TestMutualRecursionB;
