-- Generated by the protocol buffer compiler.  DO NOT EDIT!
-- source: unittest.proto

pragma Ada_2012;

package body Unittest.SparseEnumMessage is
  ---------------------------------------------------------------------------
  -- Inherited functions and procedures from Protocol_Buffers.Message -------
  ---------------------------------------------------------------------------

  procedure Clear
    (The_Message : in out Unittest.SparseEnumMessage.Instance) is
  begin
    if (The_Message.Has_Bits (0 / 32) and Protocol_Buffers.Wire_Format.Shift_Left (16#FF#, 0 mod 32)) /= 0 then
      The_Message.Sparse_Enum := TestSparseEnum'(SPARSE_A);
    end if;
    The_Message.Has_Bits := (others => 0);
  end Clear;

  procedure Copy
    (To   : in out Unittest.SparseEnumMessage.Instance;
     From : in Unittest.SparseEnumMessage.Instance) is
  begin
    To.Clear;
    To.Merge (From);
  end Copy;

  function Get_Type_Name
    (The_Message : in Unittest.SparseEnumMessage.Instance) return Protocol_Buffers.Wire_Format.PB_String is
  begin
    return "protobuf_unittest.SparseEnumMessage";
  end Get_Type_Name;

  function Is_Initialized
    (The_Message : in Unittest.SparseEnumMessage.Instance) return Boolean is
  begin
    return True;
  end Is_Initialized;

  procedure Merge
    (To   : in out Unittest.SparseEnumMessage.Instance;
     From : in Unittest.SparseEnumMessage.Instance) is
  begin
    if (From.Has_Bits (0 / 32) and Protocol_Buffers.Wire_Format.Shift_Left (16#FF#, 0 mod 32)) /= 0 then
      -- optional .protobuf_unittest.TestSparseEnum sparse_enum = 1;
      if From.Has_Sparse_Enum then
        To.Set_Sparse_Enum (From.Sparse_Enum);
      end if;
    end if;
  end Merge;

  function Byte_Size
    (The_Message : in out Unittest.SparseEnumMessage.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size is
    Total_Size : Protocol_Buffers.Wire_Format.PB_Object_Size := 0;
  begin
    if (The_Message.Has_Bits (0 / 32) and Protocol_Buffers.Wire_Format.Shift_Left (16#FF#, 0 mod 32)) /= 0 then
      -- optional .protobuf_unittest.TestSparseEnum sparse_enum = 1;
      if The_Message.Has_Sparse_Enum then
        Total_Size := Total_Size + 1 + Protocol_Buffers.IO.Coded_Output_Stream.Compute_Integer_32_Size_No_Tag (Enumeration_To_PB_Int32(The_Message.Sparse_Enum));
      end if;
    end if;
    The_Message.Cached_Size := Total_Size;
    return Total_Size;
  end Byte_Size;

  procedure Serialize_With_Cached_Sizes
    (The_Message   : in Unittest.SparseEnumMessage.Instance;
     The_Coded_Output_Stream : in
       Protocol_Buffers.IO.Coded_Output_Stream.Instance) is
  begin
    -- optional .protobuf_unittest.TestSparseEnum sparse_enum = 1;
    if The_Message.Has_Sparse_Enum then
      Protocol_Buffers.IO.Coded_Output_Stream.Write_Integer_32 (The_Coded_Output_Stream, 1, Enumeration_To_PB_Int32(The_Message.Sparse_Enum));
    end if;
  end Serialize_With_Cached_Sizes;

  procedure Merge_Partial_From_Coded_Input_Stream
    (The_Message   : in out Unittest.SparseEnumMessage.Instance;
     The_Coded_Input_Stream : in out
       Protocol_Buffers.IO.Coded_Input_Stream.Instance) is
    Tag : Protocol_Buffers.Wire_Format.PB_UInt32;
  begin
    Tag := The_Coded_Input_Stream.Read_Tag;
    while Tag /= 0 loop
      case Protocol_Buffers.Wire_Format.Get_Tag_Field_Number (Tag) is
      -- optional .protobuf_unittest.TestSparseEnum sparse_enum = 1;
      when 1 =>
        if Protocol_Buffers.Wire_Format.Get_Tag_Wire_Type (Tag) =
          Protocol_Buffers.Wire_Format.VARINT then
          The_Message.Sparse_Enum := PB_Int32_To_Enumeration(The_Coded_Input_Stream.Read_Integer_32);
          The_Message.Set_Has_Sparse_Enum;
        end if;
      when others =>
        declare
          Dummy : Protocol_Buffers.Wire_Format.PB_Bool;
          pragma Unreferenced (Dummy);
        begin
          Dummy := The_Coded_Input_Stream.Skip_Field (Tag);
          return;
        end;
      end case;
      Tag := The_Coded_Input_Stream.Read_Tag;
    end loop;
  end Merge_Partial_From_Coded_Input_Stream;

  function Get_Cached_Size
    (The_Message : in Unittest.SparseEnumMessage.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size is
  begin
    return The_Message.Cached_Size;
  end Get_Cached_Size;

  overriding
  procedure Finalize
    (The_Message : in out Unittest.SparseEnumMessage.Instance) is
  begin
    null;
  end Finalize;

  ---------------------------------------------------------------------------
  -- Field accessor definitions ---------------------------------------------
  ---------------------------------------------------------------------------

  -- optional .protobuf_unittest.TestSparseEnum sparse_enum = 1;
  function Has_Sparse_Enum
    (The_Message : in SparseEnumMessage.Instance) return Boolean is
  begin
    return (The_Message.Has_Bits(0) and 16#00000001#) /= 0;
  end Has_Sparse_Enum;

  procedure Set_Has_Sparse_Enum
    (The_Message : in out SparseEnumMessage.Instance) is
  begin
    The_Message.Has_Bits(0) := The_Message.Has_Bits(0) or 16#00000001#;
  end Set_Has_Sparse_Enum;

  procedure Clear_Has_Sparse_Enum
    (The_Message : in out SparseEnumMessage.Instance) is
  begin
    The_Message.Has_Bits(0) := The_Message.Has_Bits(0) and (not 16#00000001#);
  end Clear_Has_Sparse_Enum;

  procedure Clear_Sparse_Enum
    (The_Message : in out SparseEnumMessage.Instance) is
  begin
    The_Message.Sparse_Enum := TestSparseEnum'(SPARSE_A);
    The_Message.Clear_Has_Sparse_Enum;
  end Clear_Sparse_Enum;

  function Get_Sparse_Enum
    (The_Message : in SparseEnumMessage.Instance) return TestSparseEnum is
  begin
    return The_Message.Sparse_Enum;
  end Get_Sparse_Enum;

  procedure Set_Sparse_Enum
    (The_Message : in out SparseEnumMessage.Instance;
     Value : in TestSparseEnum) is
  begin
    Set_Has_Sparse_Enum (The_Message);
    The_Message.Sparse_Enum := Value;
  end Set_Sparse_Enum;

end Unittest.SparseEnumMessage;
