all:
	${MAKE} -C any
	${MAKE} -C basic_test
	${MAKE} -C basic_test_proto2
	${MAKE} -C benchmark_message1_proto2
	${MAKE} -C benchmark_message1_proto3
	${MAKE} -C benchmark_message3_7
	${MAKE} -C benchmark_message3_8
	${MAKE} -C benchmark_message4_3
	${MAKE} -C benchmarks
	${MAKE} -C conformance
	${MAKE} -C data
#	${MAKE} -C default_value_test
#	${MAKE} -C deprecated_file
#	${MAKE} -C descriptor
	${MAKE} -C duration
#	${MAKE} -C echo
	${MAKE} -C empty
#	${MAKE} -C generated_code
#	${MAKE} -C generated_code_proto2
	${MAKE} -C lazy_fields_lite
#	${MAKE} -C map_for_proto2_lite_test
#	${MAKE} -C map_for_proto2_test
	${MAKE} -C map_initialization_order_test
#	${MAKE} -C map_lite_test
#	${MAKE} -C map_test
	${MAKE} -C message_set_extensions
	${MAKE} -C more_extensions
	${MAKE} -C more_messages
	${MAKE} -C nested_builders_test
	${MAKE} -C non_nested_extension
	${MAKE} -C non_nested_extension_lite
#	${MAKE} -C no_package
	${MAKE} -C outer_class_name_test
	${MAKE} -C outer_class_name_test2
	${MAKE} -C outer_class_name_test3
#	${MAKE} -C proto3
	${MAKE} -C source_context
	${MAKE} -C test11
#	${MAKE} -C test12
	${MAKE} -C test13
	${MAKE} -C test14
	${MAKE} -C test3
	${MAKE} -C test5
	${MAKE} -C test6
	${MAKE} -C test8
	${MAKE} -C test9
	${MAKE} -C test_bad_identifiers
	${MAKE} -C test_check_utf8
	${MAKE} -C test_check_utf8_size
#	${MAKE} -C test_descriptors
	${MAKE} -C testempty
	${MAKE} -C test_import
	${MAKE} -C test_import_proto2
	${MAKE} -C test_include
#	${MAKE} -C test_no_namespace
#	${MAKE} -C test_prefix
#	${MAKE} -C test_reserved_enum_lower
#	${MAKE} -C test_reserved_enum_upper
#	${MAKE} -C test_reserved_enum_value_lower
#	${MAKE} -C test_reserved_enum_value_upper
#	${MAKE} -C test_reserved_message_lower
#	${MAKE} -C test_reserved_message_upper
#	${MAKE} -C test_service
	${MAKE} -C timestamp
	${MAKE} -C unittest_cycle
	${MAKE} -C unittest_deprecated
	${MAKE} -C unittest_deprecated_file
#	${MAKE} -C unittest_drop_unknown_fields
	${MAKE} -C unittest_empty
	${MAKE} -C unittest_enormous_descriptor
	${MAKE} -C unittest_issues
	${MAKE} -C unittest_lazy_dependencies_enum
	${MAKE} -C unittest_mset_wire_format
	${MAKE} -C unittest_no_arena_import
	${MAKE} -C unittest_no_arena_lite
#	${MAKE} -C unittest_no_generic_services
	${MAKE} -C unittest_preserve_unknown_enum
	${MAKE} -C unittest_preserve_unknown_enum2
#	${MAKE} -C unittest_runtime_proto3
