-- Generated by the protocol buffer compiler.  DO NOT EDIT!
-- source: unittest.proto

pragma Ada_2012;

with Unittest.TestMutualRecursionB;

package body Unittest.TestMutualRecursionA is
  ---------------------------------------------------------------------------
  -- Inherited functions and procedures from Protocol_Buffers.Message -------
  ---------------------------------------------------------------------------

  procedure Clear
    (The_Message : in out Unittest.TestMutualRecursionA.Instance) is
  begin
    if (The_Message.Has_Bits (0 / 32) and Protocol_Buffers.Wire_Format.Shift_Left (16#FF#, 0 mod 32)) /= 0 then
      if The_Message.Has_Bb then
        The_Message.Clear_Has_Bb;
        declare
          Temp : Protocol_Buffers.Message.Instance_Access := Protocol_Buffers.Message.Instance_Access(The_Message.Bb);
        begin
          Protocol_Buffers.Message.Free (Temp);
          The_Message.Bb := null;
        end;
      end if;
    end if;
    The_Message.Has_Bits := (others => 0);
  end Clear;

  procedure Copy
    (To   : in out Unittest.TestMutualRecursionA.Instance;
     From : in Unittest.TestMutualRecursionA.Instance) is
  begin
    To.Clear;
    To.Merge (From);
  end Copy;

  function Get_Type_Name
    (The_Message : in Unittest.TestMutualRecursionA.Instance) return Protocol_Buffers.Wire_Format.PB_String is
  begin
    return "protobuf_unittest.TestMutualRecursionA";
  end Get_Type_Name;

  function Is_Initialized
    (The_Message : in Unittest.TestMutualRecursionA.Instance) return Boolean is
  begin
    return True;
  end Is_Initialized;

  procedure Merge
    (To   : in out Unittest.TestMutualRecursionA.Instance;
     From : in Unittest.TestMutualRecursionA.Instance) is
  begin
    if (From.Has_Bits (0 / 32) and Protocol_Buffers.Wire_Format.Shift_Left (16#FF#, 0 mod 32)) /= 0 then
      -- optional .protobuf_unittest.TestMutualRecursionB bb = 1;
      if From.Has_Bb then
        To.Get_Bb.Merge (From.Bb.all);
      end if;
    end if;
  end Merge;

  function Byte_Size
    (The_Message : in out Unittest.TestMutualRecursionA.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size is
    Total_Size : Protocol_Buffers.Wire_Format.PB_Object_Size := 0;
  begin
    if (The_Message.Has_Bits (0 / 32) and Protocol_Buffers.Wire_Format.Shift_Left (16#FF#, 0 mod 32)) /= 0 then
      -- optional .protobuf_unittest.TestMutualRecursionB bb = 1;
      if The_Message.Has_Bb then
        Total_Size := Total_Size + 1 + Protocol_Buffers.IO.Coded_Output_Stream.Compute_Message_Size_No_Tag (The_Message.Bb.all);
      end if;
    end if;
    The_Message.Cached_Size := Total_Size;
    return Total_Size;
  end Byte_Size;

  procedure Serialize_With_Cached_Sizes
    (The_Message   : in Unittest.TestMutualRecursionA.Instance;
     The_Coded_Output_Stream : in
       Protocol_Buffers.IO.Coded_Output_Stream.Instance) is
  begin
    -- optional .protobuf_unittest.TestMutualRecursionB bb = 1;
    if The_Message.Has_Bb then
      The_Coded_Output_Stream.Write_Message (1, The_Message.Bb.all);
    end if;
  end Serialize_With_Cached_Sizes;

  procedure Merge_Partial_From_Coded_Input_Stream
    (The_Message   : in out Unittest.TestMutualRecursionA.Instance;
     The_Coded_Input_Stream : in out
       Protocol_Buffers.IO.Coded_Input_Stream.Instance) is
    Tag : Protocol_Buffers.Wire_Format.PB_UInt32;
  begin
    Tag := The_Coded_Input_Stream.Read_Tag;
    while Tag /= 0 loop
      case Protocol_Buffers.Wire_Format.Get_Tag_Field_Number (Tag) is
      -- optional .protobuf_unittest.TestMutualRecursionB bb = 1;
      when 1 =>
        if Protocol_Buffers.Wire_Format.Get_Tag_Wire_Type (Tag) =
          Protocol_Buffers.Wire_Format.LENGTH_DELIMITED then
          The_Coded_Input_Stream.Read_Message (The_Message.Get_Bb.all);
        end if;
      when others =>
        declare
          Dummy : Protocol_Buffers.Wire_Format.PB_Bool;
          pragma Unreferenced (Dummy);
        begin
          Dummy := The_Coded_Input_Stream.Skip_Field (Tag);
          return;
        end;
      end case;
      Tag := The_Coded_Input_Stream.Read_Tag;
    end loop;
  end Merge_Partial_From_Coded_Input_Stream;

  function Get_Cached_Size
    (The_Message : in Unittest.TestMutualRecursionA.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size is
  begin
    return The_Message.Cached_Size;
  end Get_Cached_Size;

  overriding
  procedure Finalize
    (The_Message : in out Unittest.TestMutualRecursionA.Instance) is
  begin
    declare
      Temp : Protocol_Buffers.Message.Instance_Access := Protocol_Buffers.Message.Instance_Access(The_Message.Bb);
    begin
      Protocol_Buffers.Message.Free (Temp);
      The_Message.Bb := null;
    end;
  end Finalize;

  ---------------------------------------------------------------------------
  -- Field accessor definitions ---------------------------------------------
  ---------------------------------------------------------------------------

  -- optional .protobuf_unittest.TestMutualRecursionB bb = 1;
  function Has_Bb
    (The_Message : in TestMutualRecursionA.Instance) return Boolean is
  begin
    return (The_Message.Has_Bits(0) and 16#00000001#) /= 0;
  end Has_Bb;

  procedure Set_Has_Bb
    (The_Message : in out TestMutualRecursionA.Instance) is
  begin
    The_Message.Has_Bits(0) := The_Message.Has_Bits(0) or 16#00000001#;
  end Set_Has_Bb;

  procedure Clear_Has_Bb
    (The_Message : in out TestMutualRecursionA.Instance) is
  begin
    The_Message.Has_Bits(0) := The_Message.Has_Bits(0) and (not 16#00000001#);
  end Clear_Has_Bb;

  procedure Clear_Bb
    (The_Message : in out TestMutualRecursionA.Instance) is
  begin
    The_Message.Clear_Has_Bb;
    declare
      Temp : Protocol_Buffers.Message.Instance_Access := Protocol_Buffers.Message.Instance_Access(The_Message.Bb);
    begin
      Protocol_Buffers.Message.Free (Temp);
      The_Message.Bb := null;
    end;
    The_Message.Clear_Has_Bb;
  end Clear_Bb;

  function Get_Bb
    (The_Message : in out TestMutualRecursionA.Instance) return access Unittest.TestMutualRecursionB.Instance is
    use type Unittest.TestMutualRecursionB.TestMutualRecursionB_Access;
  begin
    The_Message.Set_Has_Bb;
    if The_Message.Bb = null then
      The_Message.Bb := Unittest.TestMutualRecursionB.TestMutualRecursionB_Access'(new Unittest.TestMutualRecursionB.Instance);
    end if;
    return The_Message.Bb;
  end Get_Bb;

  function Release_Bb
    (The_Message : in out TestMutualRecursionA.Instance) return access Unittest.TestMutualRecursionB.Instance is
    Temp : access Unittest.TestMutualRecursionB.Instance;
  begin
    The_Message.Clear_Has_Bb;
    Temp := The_Message.Bb;
    The_Message.Bb := null;
    return Temp;
  end Release_Bb;

  procedure Set_Bb
    (The_Message : in out TestMutualRecursionA.Instance;
     Value : in Unittest.TestMutualRecursionB.TestMutualRecursionB_Access) is
    use type Unittest.TestMutualRecursionB.TestMutualRecursionB_Access;
    Temp : Protocol_Buffers.Message.Instance_Access := Protocol_Buffers.Message.Instance_Access (The_Message.Bb);
  begin
    Protocol_Buffers.Message.Free (Temp);
    The_Message.Bb := Value;
    if The_Message.Bb /= null then
      The_Message.Set_Has_Bb;
    else
      The_Message.Clear_Has_Bb;
    end if;
  end Set_Bb;

end Unittest.TestMutualRecursionA;
