-- Generated by the protocol buffer compiler.  DO NOT EDIT!
-- source: unittest.proto

pragma Ada_2012;

with Unittest.TestAllTypes;

package body Unittest.TestEagerMessage is
  ---------------------------------------------------------------------------
  -- Inherited functions and procedures from Protocol_Buffers.Message -------
  ---------------------------------------------------------------------------

  procedure Clear
    (The_Message : in out Unittest.TestEagerMessage.Instance) is
  begin
    if (The_Message.Has_Bits (0 / 32) and Protocol_Buffers.Wire_Format.Shift_Left (16#FF#, 0 mod 32)) /= 0 then
      if The_Message.Has_Sub_Message then
        The_Message.Clear_Has_Sub_Message;
        declare
          Temp : Protocol_Buffers.Message.Instance_Access := Protocol_Buffers.Message.Instance_Access(The_Message.Sub_Message);
        begin
          Protocol_Buffers.Message.Free (Temp);
          The_Message.Sub_Message := null;
        end;
      end if;
    end if;
    The_Message.Has_Bits := (others => 0);
  end Clear;

  procedure Copy
    (To   : in out Unittest.TestEagerMessage.Instance;
     From : in Unittest.TestEagerMessage.Instance) is
  begin
    To.Clear;
    To.Merge (From);
  end Copy;

  function Get_Type_Name
    (The_Message : in Unittest.TestEagerMessage.Instance) return Protocol_Buffers.Wire_Format.PB_String is
  begin
    return "protobuf_unittest.TestEagerMessage";
  end Get_Type_Name;

  function Is_Initialized
    (The_Message : in Unittest.TestEagerMessage.Instance) return Boolean is
  begin
    return True;
  end Is_Initialized;

  procedure Merge
    (To   : in out Unittest.TestEagerMessage.Instance;
     From : in Unittest.TestEagerMessage.Instance) is
  begin
    if (From.Has_Bits (0 / 32) and Protocol_Buffers.Wire_Format.Shift_Left (16#FF#, 0 mod 32)) /= 0 then
      -- optional .protobuf_unittest.TestAllTypes sub_message = 1 [lazy = false];
      if From.Has_Sub_Message then
        To.Get_Sub_Message.Merge (From.Sub_Message.all);
      end if;
    end if;
  end Merge;

  function Byte_Size
    (The_Message : in out Unittest.TestEagerMessage.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size is
    Total_Size : Protocol_Buffers.Wire_Format.PB_Object_Size := 0;
  begin
    if (The_Message.Has_Bits (0 / 32) and Protocol_Buffers.Wire_Format.Shift_Left (16#FF#, 0 mod 32)) /= 0 then
      -- optional .protobuf_unittest.TestAllTypes sub_message = 1 [lazy = false];
      if The_Message.Has_Sub_Message then
        Total_Size := Total_Size + 1 + Protocol_Buffers.IO.Coded_Output_Stream.Compute_Message_Size_No_Tag (The_Message.Sub_Message.all);
      end if;
    end if;
    The_Message.Cached_Size := Total_Size;
    return Total_Size;
  end Byte_Size;

  procedure Serialize_With_Cached_Sizes
    (The_Message   : in Unittest.TestEagerMessage.Instance;
     The_Coded_Output_Stream : in
       Protocol_Buffers.IO.Coded_Output_Stream.Instance) is
  begin
    -- optional .protobuf_unittest.TestAllTypes sub_message = 1 [lazy = false];
    if The_Message.Has_Sub_Message then
      The_Coded_Output_Stream.Write_Message (1, The_Message.Sub_Message.all);
    end if;
  end Serialize_With_Cached_Sizes;

  procedure Merge_Partial_From_Coded_Input_Stream
    (The_Message   : in out Unittest.TestEagerMessage.Instance;
     The_Coded_Input_Stream : in out
       Protocol_Buffers.IO.Coded_Input_Stream.Instance) is
    Tag : Protocol_Buffers.Wire_Format.PB_UInt32;
  begin
    Tag := The_Coded_Input_Stream.Read_Tag;
    while Tag /= 0 loop
      case Protocol_Buffers.Wire_Format.Get_Tag_Field_Number (Tag) is
      -- optional .protobuf_unittest.TestAllTypes sub_message = 1 [lazy = false];
      when 1 =>
        if Protocol_Buffers.Wire_Format.Get_Tag_Wire_Type (Tag) =
          Protocol_Buffers.Wire_Format.LENGTH_DELIMITED then
          The_Coded_Input_Stream.Read_Message (The_Message.Get_Sub_Message.all);
        end if;
      when others =>
        declare
          Dummy : Protocol_Buffers.Wire_Format.PB_Bool;
          pragma Unreferenced (Dummy);
        begin
          Dummy := The_Coded_Input_Stream.Skip_Field (Tag);
          return;
        end;
      end case;
      Tag := The_Coded_Input_Stream.Read_Tag;
    end loop;
  end Merge_Partial_From_Coded_Input_Stream;

  function Get_Cached_Size
    (The_Message : in Unittest.TestEagerMessage.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size is
  begin
    return The_Message.Cached_Size;
  end Get_Cached_Size;

  overriding
  procedure Finalize
    (The_Message : in out Unittest.TestEagerMessage.Instance) is
  begin
    declare
      Temp : Protocol_Buffers.Message.Instance_Access := Protocol_Buffers.Message.Instance_Access(The_Message.Sub_Message);
    begin
      Protocol_Buffers.Message.Free (Temp);
      The_Message.Sub_Message := null;
    end;
  end Finalize;

  ---------------------------------------------------------------------------
  -- Field accessor definitions ---------------------------------------------
  ---------------------------------------------------------------------------

  -- optional .protobuf_unittest.TestAllTypes sub_message = 1 [lazy = false];
  function Has_Sub_Message
    (The_Message : in TestEagerMessage.Instance) return Boolean is
  begin
    return (The_Message.Has_Bits(0) and 16#00000001#) /= 0;
  end Has_Sub_Message;

  procedure Set_Has_Sub_Message
    (The_Message : in out TestEagerMessage.Instance) is
  begin
    The_Message.Has_Bits(0) := The_Message.Has_Bits(0) or 16#00000001#;
  end Set_Has_Sub_Message;

  procedure Clear_Has_Sub_Message
    (The_Message : in out TestEagerMessage.Instance) is
  begin
    The_Message.Has_Bits(0) := The_Message.Has_Bits(0) and (not 16#00000001#);
  end Clear_Has_Sub_Message;

  procedure Clear_Sub_Message
    (The_Message : in out TestEagerMessage.Instance) is
  begin
    The_Message.Clear_Has_Sub_Message;
    declare
      Temp : Protocol_Buffers.Message.Instance_Access := Protocol_Buffers.Message.Instance_Access(The_Message.Sub_Message);
    begin
      Protocol_Buffers.Message.Free (Temp);
      The_Message.Sub_Message := null;
    end;
    The_Message.Clear_Has_Sub_Message;
  end Clear_Sub_Message;

  function Get_Sub_Message
    (The_Message : in out TestEagerMessage.Instance) return access Unittest.TestAllTypes.Instance is
    use type Unittest.TestAllTypes.TestAllTypes_Access;
  begin
    The_Message.Set_Has_Sub_Message;
    if The_Message.Sub_Message = null then
      The_Message.Sub_Message := Unittest.TestAllTypes.TestAllTypes_Access'(new Unittest.TestAllTypes.Instance);
    end if;
    return The_Message.Sub_Message;
  end Get_Sub_Message;

  function Release_Sub_Message
    (The_Message : in out TestEagerMessage.Instance) return access Unittest.TestAllTypes.Instance is
    Temp : access Unittest.TestAllTypes.Instance;
  begin
    The_Message.Clear_Has_Sub_Message;
    Temp := The_Message.Sub_Message;
    The_Message.Sub_Message := null;
    return Temp;
  end Release_Sub_Message;

  procedure Set_Sub_Message
    (The_Message : in out TestEagerMessage.Instance;
     Value : in Unittest.TestAllTypes.TestAllTypes_Access) is
    use type Unittest.TestAllTypes.TestAllTypes_Access;
    Temp : Protocol_Buffers.Message.Instance_Access := Protocol_Buffers.Message.Instance_Access (The_Message.Sub_Message);
  begin
    Protocol_Buffers.Message.Free (Temp);
    The_Message.Sub_Message := Value;
    if The_Message.Sub_Message /= null then
      The_Message.Set_Has_Sub_Message;
    else
      The_Message.Clear_Has_Sub_Message;
    end if;
  end Set_Sub_Message;

end Unittest.TestEagerMessage;
