-- Generated by the protocol buffer compiler.  DO NOT EDIT!
-- source: unittest.proto

pragma Ada_2012;

limited with Unittest.TestAllTypes.NestedMessage;

package Unittest.TestForeignNested is
  type Instance is new Protocol_Buffers.Message.Instance with private;
  type TestForeignNested_Access is access all Instance;

  ---------------------------------------------------------------------------
  -- Inherited functions and procedures from Protocol_Buffers.Message -------
  ---------------------------------------------------------------------------

  overriding
  procedure Clear
    (The_Message : in out Unittest.TestForeignNested.Instance);

  overriding
  procedure Serialize_With_Cached_Sizes
    (The_Message   : in Unittest.TestForeignNested.Instance;
     The_Coded_Output_Stream : in
       Protocol_Buffers.IO.Coded_Output_Stream.Instance);

  overriding
  procedure Merge_Partial_From_Coded_Input_Stream
    (The_Message   : in out Unittest.TestForeignNested.Instance;
     The_Coded_Input_Stream : in out
       Protocol_Buffers.IO.Coded_Input_Stream.Instance);

  overriding
  procedure Merge
    (To   : in out Unittest.TestForeignNested.Instance;
     From : in Unittest.TestForeignNested.Instance);

  overriding
  procedure Copy
    (To   : in out Unittest.TestForeignNested.Instance;
     From : in Unittest.TestForeignNested.Instance);

  overriding
  function Get_Type_Name
    (The_Message : in Unittest.TestForeignNested.Instance) return Protocol_Buffers.Wire_Format.PB_String;

  overriding
  function Byte_Size
    (The_Message : in out Unittest.TestForeignNested.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Get_Cached_Size
    (The_Message : in Unittest.TestForeignNested.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Is_Initialized
    (The_Message : in Unittest.TestForeignNested.Instance) return Boolean;

  overriding
  procedure Finalize (The_Message : in out Unittest.TestForeignNested.Instance);

  ---------------------------------------------------------------------------
  -- Field accessor declarations --------------------------------------------
  ---------------------------------------------------------------------------

  -- optional .protobuf_unittest.TestAllTypes.NestedMessage foreign_nested = 1;
  function Has_Foreign_Nested
    (The_Message : in TestForeignNested.Instance) return Boolean;
  procedure Clear_Foreign_Nested
    (The_Message : in out TestForeignNested.Instance);
  function Get_Foreign_Nested
    (The_Message : in out TestForeignNested.Instance) return access Unittest.TestAllTypes.NestedMessage.Instance;
  function Release_Foreign_Nested
    (The_Message : in out TestForeignNested.Instance) return access Unittest.TestAllTypes.NestedMessage.Instance;
  procedure Set_Foreign_Nested
    (The_Message : in out TestForeignNested.Instance;
     Value : in Unittest.TestAllTypes.NestedMessage.NestedMessage_Access);

private
  type Instance is new Protocol_Buffers.Message.Instance with record
    Foreign_Nested : access Unittest.TestAllTypes.NestedMessage.Instance;
    Has_Bits : Protocol_Buffers.Wire_Format.Has_Bits_Array_Type (0 .. (1 + 31) / 32) := (others => 0);
    Cached_Size : Protocol_Buffers.Wire_Format.PB_Object_Size := 0;
  end record;

  procedure Set_Has_Foreign_Nested (The_Message : in out Unittest.TestForeignNested.Instance);
  procedure Clear_Has_Foreign_Nested (The_Message : in out Unittest.TestForeignNested.Instance);
end Unittest.TestForeignNested;
