-- Generated by the protocol buffer compiler.  DO NOT EDIT!
-- source: unittest.proto

pragma Ada_2012;

package Unittest.TestRepeatedScalarDifferentTagSizes is
  type Instance is new Protocol_Buffers.Message.Instance with private;
  type TestRepeatedScalarDifferentTagSizes_Access is access all Instance;

  ---------------------------------------------------------------------------
  -- Inherited functions and procedures from Protocol_Buffers.Message -------
  ---------------------------------------------------------------------------

  overriding
  procedure Clear
    (The_Message : in out Unittest.TestRepeatedScalarDifferentTagSizes.Instance);

  overriding
  procedure Serialize_With_Cached_Sizes
    (The_Message   : in Unittest.TestRepeatedScalarDifferentTagSizes.Instance;
     The_Coded_Output_Stream : in
       Protocol_Buffers.IO.Coded_Output_Stream.Instance);

  overriding
  procedure Merge_Partial_From_Coded_Input_Stream
    (The_Message   : in out Unittest.TestRepeatedScalarDifferentTagSizes.Instance;
     The_Coded_Input_Stream : in out
       Protocol_Buffers.IO.Coded_Input_Stream.Instance);

  overriding
  procedure Merge
    (To   : in out Unittest.TestRepeatedScalarDifferentTagSizes.Instance;
     From : in Unittest.TestRepeatedScalarDifferentTagSizes.Instance);

  overriding
  procedure Copy
    (To   : in out Unittest.TestRepeatedScalarDifferentTagSizes.Instance;
     From : in Unittest.TestRepeatedScalarDifferentTagSizes.Instance);

  overriding
  function Get_Type_Name
    (The_Message : in Unittest.TestRepeatedScalarDifferentTagSizes.Instance) return Protocol_Buffers.Wire_Format.PB_String;

  overriding
  function Byte_Size
    (The_Message : in out Unittest.TestRepeatedScalarDifferentTagSizes.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Get_Cached_Size
    (The_Message : in Unittest.TestRepeatedScalarDifferentTagSizes.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Is_Initialized
    (The_Message : in Unittest.TestRepeatedScalarDifferentTagSizes.Instance) return Boolean;

  overriding
  procedure Finalize (The_Message : in out Unittest.TestRepeatedScalarDifferentTagSizes.Instance);

  ---------------------------------------------------------------------------
  -- Field accessor declarations --------------------------------------------
  ---------------------------------------------------------------------------

  -- repeated fixed32 repeated_fixed32 = 12;
  function Repeated_Fixed32_Size
    (The_Message : in TestRepeatedScalarDifferentTagSizes.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;
  procedure Clear_Repeated_Fixed32
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance);
  function Get_Repeated_Fixed32
    (The_Message : in TestRepeatedScalarDifferentTagSizes.Instance;
     Index : in Protocol_Buffers.Wire_Format.PB_Object_Size) return Protocol_Buffers.Wire_Format.PB_UInt32;
  procedure Set_Repeated_Fixed32
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance;
     Index : in Protocol_Buffers.Wire_Format.PB_Object_Size;
     Value : in Protocol_Buffers.Wire_Format.PB_UInt32);
  procedure Add_Repeated_Fixed32
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance;
     Value : in Protocol_Buffers.Wire_Format.PB_UInt32);

  -- repeated int32 repeated_int32 = 13;
  function Repeated_Int32_Size
    (The_Message : in TestRepeatedScalarDifferentTagSizes.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;
  procedure Clear_Repeated_Int32
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance);
  function Get_Repeated_Int32
    (The_Message : in TestRepeatedScalarDifferentTagSizes.Instance;
     Index : in Protocol_Buffers.Wire_Format.PB_Object_Size) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_Repeated_Int32
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance;
     Index : in Protocol_Buffers.Wire_Format.PB_Object_Size;
     Value : in Protocol_Buffers.Wire_Format.PB_Int32);
  procedure Add_Repeated_Int32
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance;
     Value : in Protocol_Buffers.Wire_Format.PB_Int32);

  -- repeated fixed64 repeated_fixed64 = 2046;
  function Repeated_Fixed64_Size
    (The_Message : in TestRepeatedScalarDifferentTagSizes.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;
  procedure Clear_Repeated_Fixed64
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance);
  function Get_Repeated_Fixed64
    (The_Message : in TestRepeatedScalarDifferentTagSizes.Instance;
     Index : in Protocol_Buffers.Wire_Format.PB_Object_Size) return Protocol_Buffers.Wire_Format.PB_UInt64;
  procedure Set_Repeated_Fixed64
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance;
     Index : in Protocol_Buffers.Wire_Format.PB_Object_Size;
     Value : in Protocol_Buffers.Wire_Format.PB_UInt64);
  procedure Add_Repeated_Fixed64
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance;
     Value : in Protocol_Buffers.Wire_Format.PB_UInt64);

  -- repeated int64 repeated_int64 = 2047;
  function Repeated_Int64_Size
    (The_Message : in TestRepeatedScalarDifferentTagSizes.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;
  procedure Clear_Repeated_Int64
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance);
  function Get_Repeated_Int64
    (The_Message : in TestRepeatedScalarDifferentTagSizes.Instance;
     Index : in Protocol_Buffers.Wire_Format.PB_Object_Size) return Protocol_Buffers.Wire_Format.PB_Int64;
  procedure Set_Repeated_Int64
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance;
     Index : in Protocol_Buffers.Wire_Format.PB_Object_Size;
     Value : in Protocol_Buffers.Wire_Format.PB_Int64);
  procedure Add_Repeated_Int64
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance;
     Value : in Protocol_Buffers.Wire_Format.PB_Int64);

  -- repeated float repeated_float = 262142;
  function Repeated_Float_Size
    (The_Message : in TestRepeatedScalarDifferentTagSizes.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;
  procedure Clear_Repeated_Float
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance);
  function Get_Repeated_Float
    (The_Message : in TestRepeatedScalarDifferentTagSizes.Instance;
     Index : in Protocol_Buffers.Wire_Format.PB_Object_Size) return Protocol_Buffers.Wire_Format.PB_Float;
  procedure Set_Repeated_Float
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance;
     Index : in Protocol_Buffers.Wire_Format.PB_Object_Size;
     Value : in Protocol_Buffers.Wire_Format.PB_Float);
  procedure Add_Repeated_Float
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance;
     Value : in Protocol_Buffers.Wire_Format.PB_Float);

  -- repeated uint64 repeated_uint64 = 262143;
  function Repeated_Uint64_Size
    (The_Message : in TestRepeatedScalarDifferentTagSizes.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;
  procedure Clear_Repeated_Uint64
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance);
  function Get_Repeated_Uint64
    (The_Message : in TestRepeatedScalarDifferentTagSizes.Instance;
     Index : in Protocol_Buffers.Wire_Format.PB_Object_Size) return Protocol_Buffers.Wire_Format.PB_UInt64;
  procedure Set_Repeated_Uint64
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance;
     Index : in Protocol_Buffers.Wire_Format.PB_Object_Size;
     Value : in Protocol_Buffers.Wire_Format.PB_UInt64);
  procedure Add_Repeated_Uint64
    (The_Message : in out TestRepeatedScalarDifferentTagSizes.Instance;
     Value : in Protocol_Buffers.Wire_Format.PB_UInt64);

private
  type Instance is new Protocol_Buffers.Message.Instance with record
    Repeated_Fixed32 : Protocol_Buffers.Wire_Format.PB_UInt32_Vector.Vector;
    Repeated_Int32 : Protocol_Buffers.Wire_Format.PB_Int32_Vector.Vector;
    Repeated_Fixed64 : Protocol_Buffers.Wire_Format.PB_UInt64_Vector.Vector;
    Repeated_Int64 : Protocol_Buffers.Wire_Format.PB_Int64_Vector.Vector;
    Repeated_Float : Protocol_Buffers.Wire_Format.PB_Float_Vector.Vector;
    Repeated_Uint64 : Protocol_Buffers.Wire_Format.PB_UInt64_Vector.Vector;
    Has_Bits : Protocol_Buffers.Wire_Format.Has_Bits_Array_Type (0 .. (6 + 31) / 32) := (others => 0);
    Cached_Size : Protocol_Buffers.Wire_Format.PB_Object_Size := 0;
  end record;

end Unittest.TestRepeatedScalarDifferentTagSizes;
