-- Generated by the protocol buffer compiler.  DO NOT EDIT!
-- source: unittest.proto

pragma Ada_2012;

package Unittest.TestRecursiveMessage is
  type Instance is new Protocol_Buffers.Message.Instance with private;
  type TestRecursiveMessage_Access is access all Instance;

  ---------------------------------------------------------------------------
  -- Inherited functions and procedures from Protocol_Buffers.Message -------
  ---------------------------------------------------------------------------

  overriding
  procedure Clear
    (The_Message : in out Unittest.TestRecursiveMessage.Instance);

  overriding
  procedure Serialize_With_Cached_Sizes
    (The_Message   : in Unittest.TestRecursiveMessage.Instance;
     The_Coded_Output_Stream : in
       Protocol_Buffers.IO.Coded_Output_Stream.Instance);

  overriding
  procedure Merge_Partial_From_Coded_Input_Stream
    (The_Message   : in out Unittest.TestRecursiveMessage.Instance;
     The_Coded_Input_Stream : in out
       Protocol_Buffers.IO.Coded_Input_Stream.Instance);

  overriding
  procedure Merge
    (To   : in out Unittest.TestRecursiveMessage.Instance;
     From : in Unittest.TestRecursiveMessage.Instance);

  overriding
  procedure Copy
    (To   : in out Unittest.TestRecursiveMessage.Instance;
     From : in Unittest.TestRecursiveMessage.Instance);

  overriding
  function Get_Type_Name
    (The_Message : in Unittest.TestRecursiveMessage.Instance) return Protocol_Buffers.Wire_Format.PB_String;

  overriding
  function Byte_Size
    (The_Message : in out Unittest.TestRecursiveMessage.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Get_Cached_Size
    (The_Message : in Unittest.TestRecursiveMessage.Instance) return Protocol_Buffers.Wire_Format.PB_Object_Size;

  overriding
  function Is_Initialized
    (The_Message : in Unittest.TestRecursiveMessage.Instance) return Boolean;

  overriding
  procedure Finalize (The_Message : in out Unittest.TestRecursiveMessage.Instance);

  ---------------------------------------------------------------------------
  -- Field accessor declarations --------------------------------------------
  ---------------------------------------------------------------------------

  -- optional .protobuf_unittest.TestRecursiveMessage a = 1;
  function Has_A
    (The_Message : in TestRecursiveMessage.Instance) return Boolean;
  procedure Clear_A
    (The_Message : in out TestRecursiveMessage.Instance);
  function Get_A
    (The_Message : in out TestRecursiveMessage.Instance) return access Unittest.TestRecursiveMessage.Instance;
  function Release_A
    (The_Message : in out TestRecursiveMessage.Instance) return access Unittest.TestRecursiveMessage.Instance;
  procedure Set_A
    (The_Message : in out TestRecursiveMessage.Instance;
     Value : in Unittest.TestRecursiveMessage.TestRecursiveMessage_Access);

  -- optional int32 i = 2;
  function Has_I
    (The_Message : in TestRecursiveMessage.Instance) return Boolean;
  procedure Clear_I
    (The_Message : in out TestRecursiveMessage.Instance);
  function Get_I
    (The_Message : in TestRecursiveMessage.Instance) return Protocol_Buffers.Wire_Format.PB_Int32;
  procedure Set_I
    (The_Message : in out TestRecursiveMessage.Instance;
     value : in Protocol_Buffers.Wire_Format.PB_Int32);

private
  type Instance is new Protocol_Buffers.Message.Instance with record
    A : access Unittest.TestRecursiveMessage.Instance;
    I : Protocol_Buffers.Wire_Format.PB_Int32 := 0;
    Has_Bits : Protocol_Buffers.Wire_Format.Has_Bits_Array_Type (0 .. (2 + 31) / 32) := (others => 0);
    Cached_Size : Protocol_Buffers.Wire_Format.PB_Object_Size := 0;
  end record;

  procedure Set_Has_A (The_Message : in out Unittest.TestRecursiveMessage.Instance);
  procedure Clear_Has_A (The_Message : in out Unittest.TestRecursiveMessage.Instance);
  procedure Set_Has_I (The_Message : in out Unittest.TestRecursiveMessage.Instance);
  procedure Clear_Has_I (The_Message : in out Unittest.TestRecursiveMessage.Instance);
end Unittest.TestRecursiveMessage;
